@startuml diagrammeControllers

class AccueilController{
    public create()
}

class ConnexionController{
    public create()
    public authenticate (Request request)
}

class InscriptionController{
    public create()
    public store (Request request)
}

class ProfilController{
    public create()
    public update (Request request)
}

class DeconnexionController{
    public __invoke()
}

@enduml
