@startuml

package app.Http.Controllers {
	class Controller

	class AccueilController extends Controller {
		index()
	}

	class InscriptionController extends Controller {
		index()
		create(InscriptionRequest request)
	}

	class ConnexionController extends Controller{
		index()
		login(LoginRequest request)
		logout(Request request)
	}

	class RecuperationController extends Controller {
		index()
		reset(RecuperationRequest request)
	}

}

package app.Http.Helpers {
	' class ApiFetcher {
	' 	fetch(String $url)
	' }
	class GenerateurMDP {
		generer()
	}
}

package app.Http.Requests {
	class InscriptionRequest extends FormRequest {
		authorize()
		rules()
	}

	class ConnexionRequest extends FormRequest {
		authorize()
		rules()
	}

	class RecuperationRequest extends FormRequest {
		authorize()
		rules()
	}
}
class EvenementController {
	show()
	edit()
	update()
	delete()
}

class EvenementCreationController {
	show()
	store()
}

@enduml